import "./globals.css";
import Script from "next/script";
export const metadata = {
  title: "Ahmed Salman Portfolio 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
    <>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-H3R4NHHD1W"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-H3R4NHHD1W');
        `}
      </Script>
      </>
      </body>
    </html>
  );
}
